apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          resources:
{{ toYaml .Values.backend.resources | indent 12 }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: DB_HOST
              value: {{ .Values.backend.db.host }}
            - name: DB_PORT
              value: {{ .Values.backend.db.port | quote }}
            - name: DB_NAME
              value: {{ .Values.backend.db.name }}
            - name: DB_USER
              value: {{ .Values.backend.db.user }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: django-admin-secret
                  key: username
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: django-admin-secret
                  key: email
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-admin-secret
                  key: password
            - name: DJANGO_SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: django-admin-secret
                  key: username
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: django-admin-secret
                  key: email
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-admin-secret
                  key: password
            - name: ALLOWED_HOSTS
              value: {{ .Values.backend.allowedHosts | quote }}
{{- if .Values.backend.tolerations }}
      tolerations:
{{ toYaml .Values.backend.tolerations | indent 8 }}
{{- end }}
