apiVersion: v1
kind: Secret
metadata:
  name: django-admin-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.backend.admin.username | quote }}
  email: {{ .Values.backend.admin.email | quote }}
  password: {{ .Values.backend.admin.password | quote }}
