{{- if .Values.jobs.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
  namespace: {{ .Values.namespace }}
  labels:
    app: backend-migrations
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: migrate
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command: ["python", "manage.py", "migrate"]
          env:
            - name: DB_HOST
              value: {{ .Values.backend.db.host }}
            - name: DB_PORT
              value: {{ .Values.backend.db.port | quote }}
            - name: DB_NAME
              value: {{ .Values.backend.db.name }}
            - name: DB_USER
              value: {{ .Values.backend.db.user }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
  backoffLimit: 3
{{- end }}
